server:
  port: 9001
   
spring:
  application:
    name: configservice
  cloud: 
    config:
      server:
        git:
          uri: https://github.com/scup08/configservice.git 
          searchPaths: configfiles
      #label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.93.193.177:8761/eureka/





