server:
  port: 9111
   
spring:
  application:
    name: configservice
  cloud: 
    config:
      server:
        git:
          uri: https://git.coding.net/eggyer/learn-spring-cloud-config.git 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/





