server:
  port: 9011
spring:
  datasource:
    url: jdbc:mysql://47.93.193.177:3306/account_db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0 # Redis数据库索引（默认为0）
    hostName: 47.93.193.177  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      maxTotal: 20 # 连接池最大连接数（使用负值表示没有限制）
      maxIdle: 10 # 连接池中的最大空闲连接
      maxWaitMillis: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      minIdle: 5 # 连接池中的最小空闲连接
mybatis:
  typeAliasesPackage: com.lzh.account.model.entity,com.lzh.common.model.entity.account
  mapperLocations: classpath:mapper/*Mapper.xml
management:
  security:
    enabled: false