server:
  port: 9011
spring:
  datasource:
    url: jdbc:mysql://47.93.193.177:3306/account_db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 2
      max-active: 8
      min-idle: 2
      max-wait: 5000 #最大等待时间，默认启用公平锁    如要启用非公平锁设置 useUnfairLock=true
      pool-prepared-statements: false #PScache   对于有游标的数据库性能提升巨大，对于mysql 建议关闭
      max-pool-prepared-statement-per-connection-size: -1 
      max-open-prepared-statements: -1 #和上面的等价
      #validation-query: 
      #validation-query-timeout: 
      #test-on-borrow: 
      #test-on-return: 
      #test-while-idle: 
      #time-between-eviction-runs-millis: 
      #min-evictable-idle-time-millis: 
      #max-evictable-idle-time-millis: 
      filters: stat,wall #配置多个英文逗号分隔
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 47.93.193.177  #Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    pool:
      maxTotal: 20 # 连接池最大连接数（使用负值表示没有限制）
      maxIdle: 10 # 连接池中的最大空闲连接
      maxWaitMillis: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      minIdle: 5 # 连接池中的最小空闲连接
mybatis:
  typeAliasesPackage: com.lzh.account.model,com.lzh.common.model.entity.account,com.lzh.common.model.entity.auth
  mapperLocations: classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
management:
  security:
    enabled: false