server:
  port: 9011
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.26.128:3306/account_db?useSSL=false
    username: root
    password: root
mybatis:
  typeAliasesPackage: com.lzh.account.model.entity,com.lzh.common.model.entity.account
  mapperLocations: classpath:mapper/*Mapper.xml