server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://192.168.26.128:3306/test_db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: com.xhld.authenticationservice.model.entity,com.lzh.common.model.entity.authenticationservice
  mapperLocations: classpath:mapper/*Mapper.xml
management:
  security:
    enabled: false