server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://192.168.189.128:3306/zuul_db?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
management:
  security:
    enabled: false