server:
  port: 9003
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.26.128:3306/test_db?useSSL=false
    url: jdbc:mysql://47.93.193.177:3306/test_db?useSSL=false
    username: root
    password: root
mybatis:
  typeAliasesPackage: com.lzh.eurekaClientA.model
  mapperLocations: classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
management:
  security:
    enabled: false
