server:
  port: 9004
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.193.177:3306/account_db?useSSL=false
    username: root
    password: root
mybatis:
  typeAliasesPackage: com.lzh.weixinservice.model
  mapperLocations: classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
management:
  security:
    enabled: false
